baseURL: 'https://hugodiscoverpro.pages.dev'
languageCode: 'ko-kr'
title: '포스트업 - 건강의 새로운 기준'
defaultContentLanguage: 'ko'
hasCJKLanguage: true

params:
  description: '포스트업은 건강한 라이프스타일과 운동 정보를 전문적으로 다루는 건강 미디어입니다.'
  keywords: '건강, 운동, 피트니스, 다이어트, 웰빙, 건강관리, 헬스케어'
  author: '주식회사 픽펄스'
  company: '주식회사 픽펄스'
  registration: '서울,아55580'
  address: '서울특별시 구로구 구로동 197-17'
  phone: '070-8065-3076'
  email: 'info@postup.com'
  publisher: '김광호'
  editor: '김광호'
  youthProtectionOfficer: '김광호'

menu:
  main:
    - name: '건강'
      url: '/health/'
      weight: 10
    - name: '운동'
      url: '/exercise/'
      weight: 20

taxonomies:
  tag: tags
  category: categories
  author: authors

outputs:
  home: ['HTML', 'RSS', 'JSON', 'SitemapGeneral', 'SitemapNews', 'SitemapAuthors', 'SitemapPages', 'SitemapLocal', 'SitemapVideo']
  page: ['HTML']
  section: ['HTML', 'RSS']

outputFormats:
  SitemapGeneral:
    mediaType: 'application/xml'
    baseName: 'sitemap-general'
    isPlainText: true
    notAlternative: true
  SitemapNews:
    mediaType: 'application/xml'
    baseName: 'sitemap-news'
    isPlainText: true
    notAlternative: true
  SitemapAuthors:
    mediaType: 'application/xml'
    baseName: 'sitemap-authors'
    isPlainText: true
    notAlternative: true
  SitemapPages:
    mediaType: 'application/xml'
    baseName: 'sitemap-pages'
    isPlainText: true
    notAlternative: true
  SitemapLocal:
    mediaType: 'application/xml'
    baseName: 'sitemap-local'
    isPlainText: true
    notAlternative: true
  SitemapVideo:
    mediaType: 'application/xml'
    baseName: 'sitemap-video'
    isPlainText: true
    notAlternative: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: github
    lineNos: true

imaging:
  resampleFilter: lanczos
  quality: 95
  anchor: smart

sitemap:
  changefreq: daily
  priority: 0.5
  filename: sitemap.xml

related:
  includeNewer: true
  indices:
    - name: keywords
      weight: 100
    - name: tags
      weight: 80
    - name: date
      weight: 10

pagination:
  pagerSize: 12
  path: page

enableRobotsTXT: true
enableGitInfo: true

# SEO 최적화
googleAnalytics: ""
disableKinds: []

# URL 최적화
uglyURLs: false
canonifyURLs: false
relativeURLs: false

# 보안 헤더
security:
  enableInlineShortcodes: false
  funcs:
    getenv:
      - "^HUGO_"
      - "^WC_"
  http:
    methods:
      - "(?i)GET|POST"
    urls:
      - ".*"
