name = "hugodiscoverpro"
compatibility_date = "2024-01-01"

[env.production]
name = "hugodiscoverpro"

[build]
command = "hugo --gc --minify"
cwd = "."
watch_dir = "."

[[build.environment_variables]]
HUGO_VERSION = "0.147.9"

[[build.environment_variables]]
NODE_VERSION = "18"

[[build.environment_variables]]
HUGO_ENV = "production"

[[build.environment_variables]]
HUGO_ENABLEGITINFO = "true"

[build.upload]
format = "directory"
dir = "public" 