name = "123"
compatibility_date = "2024-01-01"

[env.production]
vars = { }

# Environment variables will be set in Cloudflare Pages dashboard:
# CLOUDFLARE_ACCOUNT_ID = "your-account-id"
# CLOUDFLARE_API_TOKEN = "your-api-token"

[[env.production.pages_build_output_dir]]
directory = "public" 