name: Purge Cloudflare Cache

on:
  push:
    branches: [ main ]
    paths:
      - 'content/**'
      - 'layouts/**'
      - 'static/**'
      - 'config.yaml'

jobs:
  purge-cache:
    runs-on: ubuntu-latest
    
    steps:
    - name: Purge Cloudflare cache
      uses: jakejarvis/cloudflare-purge-action@master
      env:
        CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
        PURGE_URLS: |
          ${{ secrets.SITE_URL }}
          ${{ secrets.SITE_URL }}/automotive/
          ${{ secrets.SITE_URL }}/economy/
          ${{ secrets.SITE_URL }}/authors/
          ${{ secrets.SITE_URL }}/sitemap.xml
          ${{ secrets.SITE_URL }}/index.json 